### ISSUE TITLE
Conflict with Imager

### ISSUE THREAD

**Issue by LouisCuvelier** [craft-snippets/craft-table-of-contents#1]
Hi,

I would like to use this plugin but a conflict with [Imager](https://github.com/aelvan/Imager-Craft) seems to happen.

Here's the error I'm facing : 
`Cannot declare class aelvan\imager\models\Settings, because the name is already in use`

It appears when I'm using `craft.toc.getLinks()`

**Comment by piotrpog** [comment]
@LouisCuvelier Hi, sorry for late reply.
I think i know what is the problem and there will be a fix in few days.

**Comment by LouisCuvelier** [comment]
Great ! Thanks !

**Comment by piotrpog** [comment]
@LouisCuvelier 
This error should be fixed with the latest release. if it still occurs, please inform me.

**Comment by LouisCuvelier** [comment]
Working great. Thank you !
