### ISSUE TITLE
HTML is rendered as escaped in output

### ISSUE THREAD

**Issue by joshwalsh** [craft-snippets/craft-table-of-contents#5]
Hello,

Great plugin.  I found an issue today where if one of the headlines in your content contains markup (say an `<em>` tag to add emphasis part of the headline) then the output of the table of contents renders the html escaped version of that headline.   As a result, the "<em>" is rendered to the browser, rather than rendering the tag itself.

## Steps to Duplicate

If the content being parsed contains:

```
<h2>This is a <em>Test</em></h2>
```

Then rendered with code similar to this:

```
{% set tableOfContents = craft.toc.getLinks(articleContent) %}
<ul class="toc">
{% nav tocLink in tableOfContents %}
	<li>
		<a href="{{ tocLink.hash }}">{{ tocLink.text }}</a>
		{% ifchildren %}
			<ul>
				{% children %}
			</ul>
		{% endifchildren %}
	</li>
{% endnav %}
</ul>
```

This renders as:

```
<ul class="toc">
  <li>
    <a href="#...">This is a &lt;em&gt;Test&lt;/em&gt;</a>
  </li>
</ul>
```

**Comment by piotrpog** [comment]
@joshwalsh 
Thanks for pointing this out. Will look into this soon.

**Comment by joshwalsh** [comment]
Hey @piotrpog I hope you are well.   Wanted to see if you were considering a fix for this?   If not, would you be open to a pull request to fix it?

![Screenshot 2024-03-24 at 12 48 51 PM](https://github.com/craft-snippets/craft-table-of-contents/assets/19155/82df84f3-3d06-47c9-896a-7953b9635984)

**Comment by piotrpog** [comment]
Hi!
Sorry for the delay, and thanks for reminding me of this issue. 

I don't think PR will be needed, as I just released fix to this issue. I also added option to strip tags from links text (fourth parameter of `getLinks()` method). Can you confirm that it works fine on your side?

By the way, i was thinking of also adding option for rare case when someone includes <a> tag inside header, which would result in generated table of contents link also having this link from original header inside. I think in this case it would be best to change this link to something like span element. What do you think?

**Comment by joshwalsh** [comment]
Hi @piotrpog.  Thanks for the fast response.  I was drafting a pull request for a similar behavior when this came in.  I'll pull your stuff down today and let you know how it works for me.

In my opinion, if someone includes a link in the header tab you can strip the link.  After all, it becomes a link in the TOC, and having nested links is invalid.

If you are interested in seeing my case in practice, I use an `em` tag to add stylistic emphasis to my headlines like you see throughout articles like this: https://jazz-library.com/articles/tritone-substitution/

**Comment by joshwalsh** [comment]
@piotrpog Fix works great.  Cheers!
